version: '3.8'
services:
  frontend:
    container_name: frontend-web-jtk
    image: frontend-web-jtk
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    networks:
      - default

  cms-geowisata:
    container_name: cms-web-jtk
    image: cms-web-jtk
    build:
      context: cms-web-jtk
      dockerfile: cms-web-jtk.Dockerfile
    command: ["yarn", "start"]